import 'match_model.dart';
import 'venue_model.dart';

class DemoData {
  static List<Match> getDemoMatches() {
    return [
      // Football match
      Match(
        id: 'match_1',
        title: 'Weekend Football Session',
        description: 'Join us for an exciting football game at Al Wasl Sports Club. All skill levels welcome!',
        format: GameFormats.futsal,
        venue: const Venue(
          id: 'venue_1',
          name: 'Al Wasl Sports Club',
          location: 'Al Jaddaf, Dubai',
          imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
          rating: 4.8,
          amenities: ['Parking', 'Shower', 'Equipment', 'Lighting'],
        ),
        startTime: DateTime.now().add(const Duration(days: 2, hours: 18)),
        duration: const Duration(minutes: 90),
        price: 200.0,
        maxParticipants: 10,
        participants: [
          Participant(
            id: 'user_1',
            name: 'Ahmed Hassan',
            avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            joinedAt: DateTime.now().subtract(const Duration(days: 1)),
            isOrganizer: true,
            skillLevel: 'Advanced',
            gamesPlayed: 45,
          ),
          Participant(
            id: 'user_2',
            name: 'Mohammed Ali',
            avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
            joinedAt: DateTime.now().subtract(const Duration(hours: 12)),
            skillLevel: 'Intermediate',
            gamesPlayed: 23,
          ),
          Participant(
            id: 'user_3',
            name: 'Omar Khalil',
            avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
            joinedAt: DateTime.now().subtract(const Duration(hours: 6)),
            skillLevel: 'Beginner',
            gamesPlayed: 8,
          ),
          Participant(
            id: 'user_4',
            name: 'Youssef Ahmed',
            avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150',
            joinedAt: DateTime.now().subtract(const Duration(hours: 3)),
            skillLevel: 'Intermediate',
            gamesPlayed: 31,
          ),
          Participant(
            id: 'user_5',
            name: 'Karim Mahmoud',
            avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            joinedAt: DateTime.now().subtract(const Duration(hours: 1)),
            skillLevel: 'Advanced',
            gamesPlayed: 67,
          ),
        ],
        waitlist: [
          Participant(
            id: 'user_6',
            name: 'Hassan Ibrahim',
            avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
            joinedAt: DateTime.now().subtract(const Duration(minutes: 30)),
            skillLevel: 'Intermediate',
            gamesPlayed: 19,
          ),
        ],
        organizer: Participant(
          id: 'user_1',
          name: 'Ahmed Hassan',
          avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
          joinedAt: DateTime.now().subtract(const Duration(days: 1)),
          isOrganizer: true,
          skillLevel: 'Advanced',
          gamesPlayed: 45,
        ),
        skillLevel: 'Mixed',
        amenities: ['Parking', 'Shower', 'Equipment', 'Lighting'],
        createdAt: DateTime.now().subtract(const Duration(days: 3)),
      ),

      // Basketball match
      Match(
        id: 'match_2',
        title: 'Evening Basketball',
        description: 'Fast-paced 3v3 basketball game. Bring your A-game!',
        format: GameFormats.basketball3v3,
        venue: const Venue(
          id: 'venue_2',
          name: 'Al Nasr Basketball Arena',
          location: 'Oud Metha, Dubai',
          imageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800',
          rating: 4.6,
          amenities: ['Parking', 'Shower', 'Equipment'],
        ),
        startTime: DateTime.now().add(const Duration(days: 1, hours: 20)),
        duration: const Duration(minutes: 60),
        price: 150.0,
        maxParticipants: 6,
        participants: [
          Participant(
            id: 'user_7',
            name: 'Amr Salah',
            avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
            joinedAt: DateTime.now().subtract(const Duration(days: 2)),
            isOrganizer: true,
            skillLevel: 'Advanced',
            gamesPlayed: 89,
          ),
          Participant(
            id: 'user_8',
            name: 'Tarek Mostafa',
            avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150',
            joinedAt: DateTime.now().subtract(const Duration(hours: 18)),
            skillLevel: 'Intermediate',
            gamesPlayed: 42,
          ),
          Participant(
            id: 'user_9',
            name: 'Wael Kamal',
            avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            joinedAt: DateTime.now().subtract(const Duration(hours: 12)),
            skillLevel: 'Advanced',
            gamesPlayed: 73,
          ),
        ],
        organizer: Participant(
          id: 'user_7',
          name: 'Amr Salah',
          avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
          joinedAt: DateTime.now().subtract(const Duration(days: 2)),
          isOrganizer: true,
          skillLevel: 'Advanced',
          gamesPlayed: 89,
        ),
        skillLevel: 'Advanced',
        amenities: ['Parking', 'Shower', 'Equipment'],
        createdAt: DateTime.now().subtract(const Duration(days: 4)),
      ),

      // Tennis match
      Match(
        id: 'match_3',
        title: 'Tennis Doubles',
        description: 'Friendly tennis doubles game. All levels welcome!',
        format: GameFormats.tennisDoubles,
        venue: const Venue(
          id: 'venue_3',
          name: 'Dubai Tennis Stadium',
          location: 'Garhoud, Dubai',
          imageUrl: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800',
          rating: 4.9,
          amenities: ['Parking', 'Shower', 'Equipment', 'Food & Drinks'],
        ),
        startTime: DateTime.now().add(const Duration(days: 3, hours: 16)),
        duration: const Duration(minutes: 120),
        price: 300.0,
        maxParticipants: 4,
        participants: [
          Participant(
            id: 'user_10',
            name: 'Nadia El-Sayed',
            avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150',
            joinedAt: DateTime.now().subtract(const Duration(days: 1)),
            isOrganizer: true,
            skillLevel: 'Intermediate',
            gamesPlayed: 28,
          ),
          Participant(
            id: 'user_11',
            name: 'Layla Ahmed',
            avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
            joinedAt: DateTime.now().subtract(const Duration(hours: 24)),
            skillLevel: 'Beginner',
            gamesPlayed: 12,
          ),
        ],
        organizer: Participant(
          id: 'user_10',
          name: 'Nadia El-Sayed',
          avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150',
          joinedAt: DateTime.now().subtract(const Duration(days: 1)),
          isOrganizer: true,
          skillLevel: 'Intermediate',
          gamesPlayed: 28,
        ),
        skillLevel: 'Mixed',
        amenities: ['Parking', 'Shower', 'Equipment', 'Food & Drinks'],
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
      ),

      // Free match
      Match(
        id: 'match_4',
        title: 'Free Football Practice',
        description: 'Free football practice session. Come join us for some fun!',
        format: GameFormats.competitive,
        venue: const Venue(
          id: 'venue_4',
          name: 'Mushrif Park Field',
          location: 'Mushrif, Dubai',
          imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
          rating: 4.2,
          amenities: ['Equipment'],
        ),
        startTime: DateTime.now().add(const Duration(days: 5, hours: 17)),
        duration: const Duration(minutes: 75),
        price: 0.0, // Free
        maxParticipants: 12,
        participants: [
          Participant(
            id: 'user_12',
            name: 'Samir Ibrahim',
            avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            joinedAt: DateTime.now().subtract(const Duration(days: 3)),
            isOrganizer: true,
            skillLevel: 'Intermediate',
            gamesPlayed: 34,
          ),
          Participant(
            id: 'user_13',
            name: 'Hany Mohamed',
            avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
            joinedAt: DateTime.now().subtract(const Duration(days: 2)),
            skillLevel: 'Beginner',
            gamesPlayed: 5,
          ),
          Participant(
            id: 'user_14',
            name: 'Mina George',
            avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
            joinedAt: DateTime.now().subtract(const Duration(days: 1)),
            skillLevel: 'Advanced',
            gamesPlayed: 56,
          ),
          Participant(
            id: 'user_15',
            name: 'Bassem Adel',
            avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150',
            joinedAt: DateTime.now().subtract(const Duration(hours: 12)),
            skillLevel: 'Intermediate',
            gamesPlayed: 21,
          ),
          Participant(
            id: 'user_16',
            name: 'Sherif Omar',
            avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            joinedAt: DateTime.now().subtract(const Duration(hours: 6)),
            skillLevel: 'Beginner',
            gamesPlayed: 3,
          ),
          Participant(
            id: 'user_17',
            name: 'Khaled Ali',
            avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
            joinedAt: DateTime.now().subtract(const Duration(hours: 3)),
            skillLevel: 'Intermediate',
            gamesPlayed: 18,
          ),
        ],
        organizer: Participant(
          id: 'user_12',
          name: 'Samir Ibrahim',
          avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
          joinedAt: DateTime.now().subtract(const Duration(days: 3)),
          isOrganizer: true,
          skillLevel: 'Intermediate',
          gamesPlayed: 34,
        ),
        skillLevel: 'Mixed',
        amenities: ['Equipment'],
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
      ),

      // Full match
      Match(
        id: 'match_5',
        title: 'Padel Championship',
        description: 'Competitive padel doubles game. High level players only.',
        format: GameFormats.padelDoubles,
        venue: const Venue(
          id: 'venue_5',
          name: 'Padel Pro UAE',
          location: 'Al Quoz, Dubai',
          imageUrl: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800',
          rating: 4.7,
          amenities: ['Parking', 'Shower', 'Equipment', 'AC', 'Food & Drinks'],
        ),
        startTime: DateTime.now().add(const Duration(days: 1, hours: 19)),
        duration: const Duration(minutes: 90),
        price: 400.0,
        maxParticipants: 4,
        participants: [
          Participant(
            id: 'user_18',
            name: 'Ramy Hassan',
            avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
            joinedAt: DateTime.now().subtract(const Duration(days: 2)),
            isOrganizer: true,
            skillLevel: 'Professional',
            gamesPlayed: 156,
          ),
          Participant(
            id: 'user_19',
            name: 'Adel Mahmoud',
            avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150',
            joinedAt: DateTime.now().subtract(const Duration(days: 1)),
            skillLevel: 'Professional',
            gamesPlayed: 134,
          ),
          Participant(
            id: 'user_20',
            name: 'Omar Khalil',
            avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            joinedAt: DateTime.now().subtract(const Duration(hours: 18)),
            skillLevel: 'Professional',
            gamesPlayed: 98,
          ),
          Participant(
            id: 'user_21',
            name: 'Karim Salah',
            avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
            joinedAt: DateTime.now().subtract(const Duration(hours: 12)),
            skillLevel: 'Professional',
            gamesPlayed: 112,
          ),
        ],
        organizer: Participant(
          id: 'user_18',
          name: 'Ramy Hassan',
          avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
          joinedAt: DateTime.now().subtract(const Duration(days: 2)),
          isOrganizer: true,
          skillLevel: 'Professional',
          gamesPlayed: 156,
        ),
        skillLevel: 'Professional',
        amenities: ['Parking', 'Shower', 'Equipment', 'AC', 'Food & Drinks'],
        createdAt: DateTime.now().subtract(const Duration(days: 3)),
      ),

      // Cricket match
      Match(
        id: 'match_6',
        title: 'Weekend Cricket Practice',
        description: 'Join us for cricket practice session. All skill levels welcome!',
        format: GameFormats.cricketPractice,
        venue: const Venue(
          id: 'venue_6',
          name: 'Sharjah Cricket Stadium',
          location: 'Sharjah, UAE',
          imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800',
          rating: 4.5,
          amenities: ['Parking', 'Shower', 'Equipment', 'Nets'],
        ),
        startTime: DateTime.now().add(const Duration(days: 2, hours: 16)),
        duration: const Duration(minutes: 120),
        price: 250.0,
        maxParticipants: 6,
        participants: [
          Participant(
            id: 'user_22',
            name: 'Ahmed Cricket',
            avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            joinedAt: DateTime.now().subtract(const Duration(days: 1)),
            isOrganizer: true,
            skillLevel: 'Intermediate',
            gamesPlayed: 25,
          ),
          Participant(
            id: 'user_23',
            name: 'Mohammed Bowler',
            avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
            joinedAt: DateTime.now().subtract(const Duration(hours: 12)),
            skillLevel: 'Advanced',
            gamesPlayed: 45,
          ),
        ],
        organizer: Participant(
          id: 'user_22',
          name: 'Ahmed Cricket',
          avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
          joinedAt: DateTime.now().subtract(const Duration(days: 1)),
          isOrganizer: true,
          skillLevel: 'Intermediate',
          gamesPlayed: 25,
        ),
        skillLevel: 'Mixed',
        amenities: ['Parking', 'Shower', 'Equipment', 'Nets'],
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
      ),

      // Cricket T20 match
      Match(
        id: 'match_7',
        title: 'T20 Cricket Tournament',
        description: 'Exciting T20 cricket tournament. Teams needed!',
        format: GameFormats.cricketT20,
        venue: const Venue(
          id: 'venue_7',
          name: 'Dubai International Cricket Stadium',
          location: 'Sports City, Dubai',
          imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800',
          rating: 4.7,
          amenities: ['Parking', 'Shower', 'Equipment', 'Pavilion', 'Food & Drinks'],
        ),
        startTime: DateTime.now().add(const Duration(days: 5, hours: 14)),
        duration: const Duration(minutes: 180),
        price: 500.0,
        maxParticipants: 22,
        participants: [
          Participant(
            id: 'user_24',
            name: 'Cricket Captain',
            avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
            joinedAt: DateTime.now().subtract(const Duration(days: 3)),
            isOrganizer: true,
            skillLevel: 'Professional',
            gamesPlayed: 120,
          ),
          Participant(
            id: 'user_25',
            name: 'Fast Bowler',
            avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150',
            joinedAt: DateTime.now().subtract(const Duration(days: 2)),
            skillLevel: 'Advanced',
            gamesPlayed: 78,
          ),
        ],
        organizer: Participant(
          id: 'user_24',
          name: 'Cricket Captain',
          avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
          joinedAt: DateTime.now().subtract(const Duration(days: 3)),
          isOrganizer: true,
          skillLevel: 'Professional',
          gamesPlayed: 120,
        ),
        skillLevel: 'Advanced',
        amenities: ['Parking', 'Shower', 'Equipment', 'Pavilion', 'Food & Drinks'],
        createdAt: DateTime.now().subtract(const Duration(days: 4)),
      ),

      // Padel match
      Match(
        id: 'match_8',
        title: 'Padel Doubles',
        description: 'Friendly padel doubles game. All levels welcome!',
        format: GameFormats.padelDoubles,
        venue: const Venue(
          id: 'venue_8',
          name: 'Padel Point',
          location: 'Jumeirah, Dubai',
          imageUrl: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800',
          rating: 4.8,
          amenities: ['Parking', 'Shower', 'Equipment', 'AC', 'Food & Drinks'],
        ),
        startTime: DateTime.now().add(const Duration(days: 3, hours: 10)),
        duration: const Duration(minutes: 90),
        price: 350.0,
        maxParticipants: 4,
        participants: [
          Participant(
            id: 'user_26',
            name: 'Padel Player 1',
            avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
            joinedAt: DateTime.now().subtract(const Duration(days: 1)),
            isOrganizer: true,
            skillLevel: 'Intermediate',
            gamesPlayed: 30,
          ),
          Participant(
            id: 'user_27',
            name: 'Padel Player 2',
            avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150',
            joinedAt: DateTime.now().subtract(const Duration(hours: 12)),
            skillLevel: 'Advanced',
            gamesPlayed: 60,
          ),
        ],
        organizer: Participant(
          id: 'user_26',
          name: 'Padel Player 1',
          avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
          joinedAt: DateTime.now().subtract(const Duration(days: 1)),
          isOrganizer: true,
          skillLevel: 'Intermediate',
          gamesPlayed: 30,
        ),
        skillLevel: 'Mixed',
        amenities: ['Parking', 'Shower', 'Equipment', 'AC', 'Food & Drinks'],
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
      ),
    ];
  }

  static Match getDemoMatch() {
    return getDemoMatches().first;
  }
} 